name: calendar_app
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  dartz: ^0.10.1
  shared_preferences: ^2.5.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  lottie: ^3.3.1
  intl: ^0.19.0
  syncfusion_flutter_datepicker: ^28.2.12
  auto_route: ^9.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  auto_route_generator: ^9.0.0
  flutter_native_splash: ^2.0.0
  flutter_lints: ^5.0.0
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  mocktail: ^1.0.4



flutter:

  uses-material-design: true

  assets:
     - lib/i18n/
     - assets/

